In [3]:
import numpy as np 
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
a.reshape(2,2) #changes the array to a 2x2 2 dimensional array

array([[1, 2],
       [3, 4]])

In [5]:
b = np.arange(24) #creates an array with 24 values starting with 0
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [6]:
c = b.reshape(2,4,3) #reshapes the arrays into 2 matrixes with 4 rows and 3 columns each
print(c)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [9]:
x = np.zeros(5,dtype=np.int)#prints zeros into an array, dtype sets the data type - defaults to a float
print(x)

[0 0 0 0 0]


In [11]:
d=np.linspace(10,20,5, endpoint=False)#takes the first two numbers and divides them into 5 parts and puts those parts into an array
print(d)

[ 10.  12.  14.  16.  18.]


In [13]:
e = np.logspace(1.0,2.0,num=10,base=2)
print(e)

[ 2.          2.16011948  2.33305808  2.5198421   2.72158     2.93946898
  3.1748021   3.42897593  3.70349885  4.        ]
