In [2]:
import numpy as np
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
s = slice(2,7,2) 
print(a[s])

[2 4 6]


In [6]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
b = a[2:7:2]
print(b)

[2 4 6]


In [9]:
print(a[2:])

[2 3 4 5 6 7 8 9]


In [10]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(c[2:])

[[7 8 9]]


In [13]:
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
d = c[[0,1,2],[0,1,0]] #array 0, select the 0th value. array 1, select value 1, etc. 

print(d)

[1 5 7]


In [19]:
e = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(e)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [22]:
row = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])
y = e[row,cols]
print(y)

[[ 0  2]
 [ 9 11]]


In [23]:
print(e)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [25]:
print (e[e>5])

[ 6  7  8  9 10 11]
